# Generated by Django 5.0 on 2024-04-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Stock Full or General used Name ', max_length=50)),
                ('script_symbol', models.CharField(help_text='Stock standard scripy_symbol name given by nse', max_length=50, unique=True)),
                ('script_id', models.IntegerField(help_text='Nse script id ')),
            ],
        ),
        migrations.CreateModel(
            name='trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.FloatField()),
                ('stoploss', models.FloatField()),
                ('target', models.FloatField()),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(models.F('script_id'), name='script_id must be unique', violation_error_message='Script_id already exist '),
        ),
    ]
