# Generated by Django 5.0 on 2024-05-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version01', '0003_fin_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fin_account',
        ),
    ]
